# Generated by Django 4.2.6 on 2024-08-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_type_incidence_model_incidence_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
